# Generated by Django 3.0.3 on 2020-04-17 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paragraphs',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
